# model_id: ./models/final_ft_10_epochs_lr2e-05_llama-3.2-vision_retain
# model_family: llama-3.2-vision

model_id: ./models/final_ft_10_epochs_lr2e-05_llava-v1.6-vicuna_full
model_family: llava-v1.6-vicuna

LoRA:
  r: 0
  alpha: 128
  dropout: 0.05

loss_type: grad_ascent
tune_vision_tower: False
tune_mm_projector: True  # True
tune_language_model: True  # True
data_path: ./dataset/full.json
split: full # retain
batch_size: 1  #3
gradient_accumulation_steps: 4
max_grad_norm: 1.0
num_epochs: 2    # 2
save_dir: models/final_ft_${num_epochs}_epochs_lr${lr}_${model_family}_${split}
save_steps: 50  # 210
lr: 1e-5
weight_decay: 0.01
seed: 233
workers: 4
lr_scheduler_type: "cosine"
warmup_ratio: 0.00
max_train_steps: -1
report_to: "wandb"
resume_from_checkpoint: ""
